### ISSUE TITLE
Scheduling Options

### ISSUE THREAD

**Issue by mhorvvitz** [alexcavender/Automatic-Export-to-CSV-for-Gravity-Forms#1]
Hi @alexcavender ,
Thanks for creating this. This is something I've been looking for a long time.

I would like to see the option to schedule the notifications beefed up. Specifically it would be great to specify a time each day, week or month when the email should be sent.

**Comment by alexcavender** [comment]
Hi @mhorvvitz 
I'm adding this as a feature / milestone and closing for now
thanks
