### ISSUE TITLE
csv output, included empty fields

### ISSUE THREAD

**Issue by ritchietomasouw** [alexcavender/Automatic-Export-to-CSV-for-Gravity-Forms#15]
Hi there,

I have a problem with the CSV output:
The output is like:

Name,City,Number
Ritchie,Soest,0001
John,Soest,0002
Richard,0003
Soest,0004

 in the example above the last 2 records is missing some values, but the empty values are not included. This way the headers isn't corresponding the value anymore.

I expected something like this as output:

Name,City,Number
Ritchie,Soest,0001
John,Soest,0002
Richard,,0003
,,Soest,0004

So empty values is shown like a ','
How can this be done?

Kind regards,
Ritchie

**Comment by alexcavender** [comment]
Hi Ritchie,

I am currently going through a backlog of several issues and will be trying my best to put out a release this month. My full time work obligations come first but if you have a pull request to fix this I will absolutely look it over and probably accept it!

Thanks,
Alex

**Comment by alexcavender** [comment]
Hi @ritchietomasouw 

The latest release should address this -- closing for now

Thanks,
Alex
