### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by patronusgo** [alexcavender/Automatic-Export-to-CSV-for-Gravity-Forms#2]
Any idea how to stop the following? It's evident on activation with no custom theme or plugins other than Gforms:

`PHP Fatal error:  Access level to GFAutomaticCSVAddOn::init_admin() must be public (as in class GFAddOn) in /var/www/html/wp-content/plugins/gravityforms-automatic-csv-export/class-gf-automatic-csv-addon.php on line 0
`

**Comment by alexcavender** [comment]
This is now fixed
