### ISSUE TITLE
Breaks signature field

### ISSUE THREAD

**Issue by glennss** [alexcavender/Automatic-Export-to-CSV-for-Gravity-Forms#21]
This addon breaks the signature field in gravity forms

**Comment by alexcavender** [comment]
Hi,

Are you using the Dev branch?

Thanks

**Comment by glennss** [comment]
No, was using the Master, will test with Dev and report back.

**Comment by glennss** [comment]
Works ok on the Dev branch

**Comment by alexcavender** [comment]
Very cool, thanks for testing that out!

**Comment by alexcavender** [comment]
Leaving this one open if you run into issues with the branch
