### ISSUE TITLE
Hard-coded default table prefix

### ISSUE THREAD

**Issue by sulym-roman** [alexcavender/Automatic-Export-to-CSV-for-Gravity-Forms#22]
File automatic_csv_export_for_gravity_forms.php
Line 30: $forms = $wpdb->get_results( "SELECT form_id, display_meta FROM **wp_rg_form_meta**" );

If a WP installation uses a custom table prefix, this line causes WordPress database error. Please fix.

_WordPress database error: [Table 'dbname.wp_rg_form_meta' doesn't exist]
SELECT form_id, display_meta FROM wp_rg_form_meta_

**Comment by alexcavender** [comment]
Just fixed this one
