### ISSUE TITLE
No emails being sent

### ISSUE THREAD

**Issue by taddmencer** [alexcavender/Automatic-Export-to-CSV-for-Gravity-Forms#27]
I was trying to get this system working. Sounds like a great plugin with a lot of great uses. However, no emails were being sent out. I set it up on Friday, hoping through the weekend it would work like a rockstar. So far, it's sent no emails. 

I'm using WP Engine
WordPress is up to date
Gravity Forms is up to date

Looking at the error logs, I do see this:

`PHP Fatal error:  Call to undefined method GravityFormsAutomaticCSVExport::get_gmt_date() in /mywebhosthere/wp-content/plugins/Automatic-Export-to-CSV-for-Gravity-Forms-master/automatic_csv_export_for_gravity_forms.php on line 230, referer: https://mywebhosthere/wp-cron.php?doing_wp_cron=1496151662.1950221061706542968750`

Any help would be really appreciated.

**Comment by taddmencer** [comment]
My guess is "No, sorry. Can't help." Which ok, that's cool. That's cool.

**Comment by 949mac** [comment]
In automatic_csv_export_for_gravity_forms.php, change all instances of `self::get_gmt_date` to `GFExport::get_gmt_date`.

**Comment by alexcavender** [comment]
Hi,

This should now be resolved in latest update

Thanks
