### ISSUE TITLE
Not Workin

### ISSUE THREAD

**Issue by ChiefNetNut** [alexcavender/Automatic-Export-to-CSV-for-Gravity-Forms#4]
Hi Alex

This is exactly the Plugin I am looking for.
I followed your instructions and then filed in my form but it doesn't seem to work if i set it hourly. can you advise  what could be wrong?

Many Thanks

**Comment by alexcavender** [comment]
Hi,

Can you try the latest update and see if you are still having this issue. Also are you able to send emails form your server normally using wp_mail() function

Thanks

**Comment by ChiefNetNut** [comment]
Hi Alex,

Thank you for your email,

I have just  installed the latest version of the plugin which I downloaded from GitHub.
I have set it to hourly and just created an entry to test it so will let you know what happens.

in terms of the wp_mail() function when the form is submitted a  version of the form is emailed to an email address is this what you are referring to.

Thanks

Nick Druce
Founder and Director
NetNutz Digital
p:	07905328772  m: 07905328772
a:	30 Church Lane, Whitefield Manchester M45 7NF
w:	 <http://netnutz.co.uk/>netnutz.co.uk <http://netnutz.co.uk/>  e: nick@netnutz.co.uk <mailto:nick@netnutz.co.uk>

 <https://www.facebook.com/NetNutz/>   <https://www.facebook.com/NetNutz/> <https://twitter.com/ChiefNetNut>   <https://twitter.com/ChiefNetNut>
    
Net-Nutz - Delivering Success Online.

The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.
 
NetNutz Digital Limited may monitor email traffic data to manage billing, to handle customer enquiries and for the prevention and detection of fraud. We may also monitor the content of emails sent to and/or from NetNutz Digital Limited or the purposes of security, staff training and to monitor quality of service.

NetNutz Digital Limited is registered in England and Wales, 30 Church Lane Whitefield Manchester M45 7NF Company No. 10236234



 <https://uk.linkedin.com/in/nickdruce>
   <https://www.facebook.com/NetNutz/> <https://twitter.com/ChiefNetNut>   <https://twitter.com/ChiefNetNut> <https://uk.linkedin.com/in/nickdruce>
 <https://uk.linkedin.com/in/nickdruce> <https://uk.linkedin.com/in/nickdruce>Net-Nutz - Delivering Success Online.

The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.
 
NetNutz Digital Limited may monitor email traffic data to manage billing, to handle customer enquiries and for the prevention and detection of fraud. We may also monitor the content of emails sent to and/or from NetNutz Digital Limited or the purposes of security, staff training and to monitor quality of service.

NetNutz Digital Limited is registered in England and Wales, 30 Church Lane Whitefield Manchester M45 7NF Company No. 10236234
 <https://uk.linkedin.com/in/nickdruce> <https://uk.linkedin.com/in/nickdruce>

**Comment by ChiefNetNut** [comment]
Hi Alex

I tried the updated version and I am still having the same issue.

What would you recommend?

Thanks

Nick


Nick Druce
Founder and Director
NetNutz Digital
p:	07905328772  m: 07905328772
a:	30 Church Lane, Whitefield Manchester M45 7NF
w:	 <http://netnutz.co.uk/>netnutz.co.uk <http://netnutz.co.uk/>  e: nick@netnutz.co.uk <mailto:nick@netnutz.co.uk>

 <https://www.facebook.com/NetNutz/>   <https://www.facebook.com/NetNutz/> <https://twitter.com/ChiefNetNut>   <https://twitter.com/ChiefNetNut>
    
Net-Nutz - Delivering Success Online.

The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.
 
NetNutz Digital Limited may monitor email traffic data to manage billing, to handle customer enquiries and for the prevention and detection of fraud. We may also monitor the content of emails sent to and/or from NetNutz Digital Limited or the purposes of security, staff training and to monitor quality of service.

NetNutz Digital Limited is registered in England and Wales, 30 Church Lane Whitefield Manchester M45 7NF Company No. 10236234



 <https://uk.linkedin.com/in/nickdruce>
   <https://www.facebook.com/NetNutz/> <https://twitter.com/ChiefNetNut>   <https://twitter.com/ChiefNetNut> <https://uk.linkedin.com/in/nickdruce>
 <https://uk.linkedin.com/in/nickdruce> <https://uk.linkedin.com/in/nickdruce>Net-Nutz - Delivering Success Online.

The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.
 
NetNutz Digital Limited may monitor email traffic data to manage billing, to handle customer enquiries and for the prevention and detection of fraud. We may also monitor the content of emails sent to and/or from NetNutz Digital Limited or the purposes of security, staff training and to monitor quality of service.

NetNutz Digital Limited is registered in England and Wales, 30 Church Lane Whitefield Manchester M45 7NF Company No. 10236234
 <https://uk.linkedin.com/in/nickdruce> <https://uk.linkedin.com/in/nickdruce>

**Comment by ritchietomasouw** [comment]
I have the same problem. Installed the latest version of the plugin, wp_mail works, but sadly no automatic export.

**Comment by alexcavender** [comment]
Hi,

If you visit http://yourwebsite.com/wp-cron.php?doing_wp_cron
Does the email get delivered? Do you see any errors on this page?

Also please check your spam folder. 

thanks

**Comment by ChiefNetNut** [comment]
Hi Alex

Thank so much for your help so far it has been great.

I went to the link like you said and it just showed up as a blank page. However the email itself came through to my inbox. Is this what is supposed to happen.
I have the setting set for a daily export so I will se what happens tomorrow.

Also When I opened the CSV file, the columns and the headings were not in the right places. e.g. place of birth was under the column heading of phone number. How do I fix this

Thanks


Nick Druce
Founder and Director
NetNutz Digital
p:	07905328772  m: 07905328772
a:	30 Church Lane, Whitefield Manchester M45 7NF
w:	 <http://netnutz.co.uk/>netnutz.co.uk <http://netnutz.co.uk/>  e: nick@netnutz.co.uk <mailto:nick@netnutz.co.uk>

 <https://www.facebook.com/NetNutz/>   <https://www.facebook.com/NetNutz/> <https://twitter.com/ChiefNetNut>   <https://twitter.com/ChiefNetNut>
    
Net-Nutz - Delivering Success Online.

The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.
 
NetNutz Digital Limited may monitor email traffic data to manage billing, to handle customer enquiries and for the prevention and detection of fraud. We may also monitor the content of emails sent to and/or from NetNutz Digital Limited or the purposes of security, staff training and to monitor quality of service.

NetNutz Digital Limited is registered in England and Wales, 30 Church Lane Whitefield Manchester M45 7NF Company No. 10236234



 <https://uk.linkedin.com/in/nickdruce>
   <https://www.facebook.com/NetNutz/> <https://twitter.com/ChiefNetNut>   <https://twitter.com/ChiefNetNut> <https://uk.linkedin.com/in/nickdruce>
 <https://uk.linkedin.com/in/nickdruce> <https://uk.linkedin.com/in/nickdruce>Net-Nutz - Delivering Success Online.

The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful.

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.
 
NetNutz Digital Limited may monitor email traffic data to manage billing, to handle customer enquiries and for the prevention and detection of fraud. We may also monitor the content of emails sent to and/or from NetNutz Digital Limited or the purposes of security, staff training and to monitor quality of service.

NetNutz Digital Limited is registered in England and Wales, 30 Church Lane Whitefield Manchester M45 7NF Company No. 10236234
 <https://uk.linkedin.com/in/nickdruce> <https://uk.linkedin.com/in/nickdruce>

**Comment by alexcavender** [comment]
What this usually means is that your wordpress Cron is not running as it should. Here's what I recommend if you use shared hosting (e.g. Hostgator, bluehost, etc)
http://support.hostgator.com/articles/specialized-help/technical/wordpress/how-to-replace-wordpress-cron-with-a-real-cron-job
