### ISSUE TITLE
Correction to GFAPI::get_entries function usage

### ISSUE THREAD

**Issue by stevetronix** [alexcavender/Automatic-Export-to-CSV-for-Gravity-Forms#5]
If a user selects to have all entries of a form emailed to them from the beginning of time, they will only be emailed a file with a maximum of 20 entries, which is the default paging setting for the GFAPI::get_entries() function. Therefore, we will need to make a change to the plugin. Right after the search criteria conditional checks in the gforms_automated_export() function, we'll need to change the line:

`$all_form_entries = GFAPI::get_entries($form_id, $search_criteria); `

to

```
/*
  * GFAPI::get_entries 
  *
  * ( $form_ids, $search_criteria = array(), $sorting = null, $paging = null, $total_count = null )
  */		

//get the total number of entries that the form has
$total_entries = GFAPI::count_entries( $form_id );
//set paging to the total number of entries for the form
$paging = array( 'offset' => 0, 'page_size' => $total_entries );
//Pass a non-null value to get the total count in the results
$total_count = 0;

$all_form_entries = GFAPI::get_entries( $form_id , $search_criteria, null, $paging, $total_count); 

```

**Comment by alexcavender** [comment]
Thank you @stevetronix , I will include this in the next release
